development:
  app_id: 396547350445717
  secret_key: 'ENV[APP_SECRET]'
test:
  app_id: 396547350445717
  secret_key: 'ENV[APP_SECRET]'
production:
  app_id: 396547350445717
  secret_key: 'ENV[APP_SECRET]'
